## Order & Product Profitability Risk Modeling

### Notebook 1 — Data Understanding & Preparation

#### Objective
Understand the dataset structure, identify how the data is organized, and prepare an order level dataset aligned with the business problem of profitability risk.

#### Key Tasks
- Load and inspect the dataset
- Understand data granularity (order-item vs order level)
- Check missing values and basic data quality
- Verify how key variables like profit are recorded
- Aggregate data from item level to order level
- Select relevant features and remove unnecessary data
- Prepare a clean dataset for further analysis

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("../data/raw/DataCoSupplyChainDataset.xlsx", nrows=5000)
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,Delay Days,Delay Flag,Delay Severity
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-03-02 22:56:00,Standard Class,-1,0,On Time
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class,1,1,1–2 Days Late
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class,0,0,On Time
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class,-1,0,On Time
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class,-2,0,On Time

In [4]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode',
       'Delay Days', 'Delay Flag ', 'Delay Severity'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 56 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Type                           5000 non-null   object
 1   Days for shipping (real)       5000 non-null   int64
 2   Days for shipment (scheduled)  5000 non-null   int64
 3   Benefit per order              5000 non-null   float64
 4   Sales per customer             5000 non-null   float64
 5   Delivery Status                5000 non-null   object
 6   Late_delivery_risk             5000 non-null   int64
 7   Category Id                    5000 non-null   int64
 8   Category Name                  5000 non-null   object
 9   Customer City                  5000 non-null   object
 10  Customer Country               5000 non-null   object
 11  Customer Email                 5000 non-null   object
 12  Customer Fname                 5000 non-null   object
 13  Customer Id                    5000 non-null   int64
 14  Customer Lname                 5000 non-null   object
 15  Customer Password              5000 non-null   object
 16  Customer Segment               5000 non-null   object
 17  Customer State                 5000 non-null   object
 18  Customer Street                5000 non-null   object
 19  Customer Zipcode               5000 non-null   int64
 20  Department Id                  5000 non-null   int64
 21  Department Name                5000 non-null   object
 22  Latitude                       5000 non-null   float64
 23  Longitude                      5000 non-null   float64
 24  Market                         5000 non-null   object
 25  Order City                     5000 non-null   object
 26  Order Country                  5000 non-null   object
 27  Order Customer Id              5000 non-null   int64
 28  order date (DateOrders)        5000 non-null   object
 29  Order Id                       5000 non-null   int64
 30  Order Item Cardprod Id         5000 non-null   int64
 31  Order Item Discount            5000 non-null   float64
 32  Order Item Discount Rate       5000 non-null   float64
 33  Order Item Id                  5000 non-null   int64
 34  Order Item Product Price       5000 non-null   float64
 35  Order Item Profit Ratio        5000 non-null   float64
 36  Order Item Quantity            5000 non-null   int64
 37  Sales                          5000 non-null   float64
 38  Order Item Total               5000 non-null   float64
 39  Order Profit Per Order         5000 non-null   float64
 40  Order Region                   5000 non-null   object
 41  Order State                    5000 non-null   object
 42  Order Status                   5000 non-null   object
 43  Order Zipcode                  282 non-null    float64
 44  Product Card Id                5000 non-null   int64
 45  Product Category Id            5000 non-null   int64
 46  Product Description            0 non-null      float64
 47  Product Image                  5000 non-null   object
 48  Product Name                   5000 non-null   object
 49  Product Price                  5000 non-null   float64
 50  Product Status                 5000 non-null   int64
 51  shipping date (DateOrders)     5000 non-null   object
 52  Shipping Mode                  5000 non-null   object
 53  Delay Days                     5000 non-null   int64
 54  Delay Flag                     5000 non-null   int64
 55  Delay Severity                 5000 non-null   object
dtypes: float64(14), int64(17), object(25)
memory usage: 2.1+ MB

In [7]:
full_df = pd.read_excel("../data/raw/DataCoSupplyChainDataset.xlsx")
full_df.to_csv("../data/raw/data.csv", index=False)

In [8]:
df = pd.read_csv("../data/raw/data.csv")
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,Delay Days,Delay Flag,Delay Severity
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-03-02 22:56:00,Standard Class,-1,0,On Time
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class,1,1,1–2 Days Late
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class,0,0,On Time
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class,-1,0,On Time
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class,-2,0,On Time

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 56 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
 53  Delay Days                     180519 non-null  int64
 54  Delay Flag                     180519 non-null  int64
 55  Delay Severity                 180519 non-null  object
dtypes: float64(15), int64(16), object(25)
memory usage: 77.1+ MB

In [10]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode',
       'Delay Days', 'Delay Flag ', 'Delay Severity'],
      dtype='object')

In [11]:
df.isnull().sum().sort_values(ascending=False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Order State                           0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Type                                  0
Order Status                          0
Order Id                              0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
Delay Days                            0
Delay Flag                            0
Order Item Cardprod Id                0
order date (DateOrders)               0
Days for shipping (real)              0
Order Customer Id                     0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Delay Severity                        0
dtype: int64

In [12]:
df['Order Id'].nunique()

65752

In [13]:
df.groupby('Order Id').size().describe()

count    65752.000000
mean         2.745453
std          1.478363
min          1.000000
25%          1.000000
50%          3.000000
75%          4.000000
max          5.000000
dtype: float64

In [14]:
# Create order-level dataset

orders_df = df.groupby('Order Id').agg({
    'Sales': 'sum',
    'Order Item Total': 'sum',
    'Order Item Discount': 'sum',
    'Order Item Quantity': 'sum',
    'Order Profit Per Order': 'sum',

    'Customer Segment': 'first',
    'Market': 'first',
    'Shipping Mode': 'first',
    'Order Region': 'first',
    'Order Country': 'first'
}).reset_index()

In [17]:
orders_df.shape

(65752, 11)

In [18]:
orders_df.head()

,Order Id,Sales,Order Item Total,Order Item Discount,Order Item Quantity,Order Profit Per Order,Customer Segment,Market,Shipping Mode,Order Region,Order Country
0,1,299.980011,239.979996,60.000000,1,88.790001,Consumer,LATAM,Standard Class,Central America,México
1,2,579.980011,529.380005,50.600000,7,195.900002,Consumer,LATAM,Standard Class,South America,Colombia
2,4,699.850010,620.870014,78.980000,14,124.090000,Home Office,LATAM,Standard Class,South America,Colombia
3,5,1129.860039,987.070007,142.789999,10,390.089995,Consumer,LATAM,Standard Class,South America,Colombia
4,7,579.920013,525.520004,54.400000,7,203.929998,Consumer,LATAM,Second Class,South America,Brasil

In [19]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65752 entries, 0 to 65751
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order Id                65752 non-null  int64
 1   Sales                   65752 non-null  float64
 2   Order Item Total        65752 non-null  float64
 3   Order Item Discount     65752 non-null  float64
 4   Order Item Quantity     65752 non-null  int64
 5   Order Profit Per Order  65752 non-null  float64
 6   Customer Segment        65752 non-null  object
 7   Market                  65752 non-null  object
 8   Shipping Mode           65752 non-null  object
 9   Order Region            65752 non-null  object
 10  Order Country           65752 non-null  object
dtypes: float64(4), int64(2), object(5)
memory usage: 5.5+ MB

In [20]:
df[['Order Id', 'Order Profit Per Order']].head(10)

   Order Id  Order Profit Per Order
0     77202               91.250000
1     75939             -249.089996
2     75938             -247.779999
3     75937               22.860001
4     75936              134.210007
5     75935               18.580000
6     75934               95.180000
7     75933               68.430000
8     75932              133.720001
9     75931              132.149994

In [21]:
df.groupby('Order Id')['Order Profit Per Order'].nunique().value_counts()

Order Profit Per Order
1    19850
4    11721
2    11460
3    11400
5    11321
Name: count, dtype: int64

In [22]:
orders_df = orders_df.rename(columns={
    'Sales': 'total_sales',
    'Order Item Total': 'total_order_value',
    'Order Item Discount': 'total_discount',
    'Order Item Quantity': 'total_quantity',
    'Order Profit Per Order': 'order_profit'
})

In [23]:
orders_df.describe()

,Order Id,total_sales,total_order_value,total_discount,total_quantity,order_profit
count,65752.000000,65752.000000,65752.000000,65752.000000,65752.000000,65752.000000
mean,39311.904216,559.446633,502.713262,56.734067,5.841328,60.331290
std,22607.334445,355.537119,320.948511,46.584295,4.169632,189.716897
min,1.000000,9.990000,7.490000,0.000000,1.000000,-4325.849979
25%,19710.750000,265.957504,244.780006,20.000000,2.000000,7.797500
50%,39434.500000,504.890008,455.950008,47.390000,5.000000,72.734999
75%,59099.250000,799.950028,721.190018,82.390002,9.000000,158.669999
max,77204.000000,3449.909988,2768.409988,681.500000,24.000000,980.280006

In [24]:
orders_df['order_profit'].describe()

count    65752.000000
mean        60.331290
std        189.716897
min      -4325.849979
25%          7.797500
50%         72.734999
75%        158.669999
max        980.280006
Name: order_profit, dtype: float64

In [25]:
orders_df.isnull().sum()

Order Id             0
total_sales          0
total_order_value    0
total_discount       0
total_quantity       0
order_profit         0
Customer Segment     0
Market               0
Shipping Mode        0
Order Region         0
Order Country        0
dtype: int64

In [26]:
orders_df.to_csv("../data/processed/orders_clean.csv", index=False)

In [27]:
pd.read_csv("../data/processed/orders_clean.csv").head()

,Order Id,total_sales,total_order_value,total_discount,total_quantity,order_profit,Customer Segment,Market,Shipping Mode,Order Region,Order Country
0,1,299.980011,239.979996,60.000000,1,88.790001,Consumer,LATAM,Standard Class,Central America,México
1,2,579.980011,529.380005,50.600000,7,195.900002,Consumer,LATAM,Standard Class,South America,Colombia
2,4,699.850010,620.870014,78.980000,14,124.090000,Home Office,LATAM,Standard Class,South America,Colombia
3,5,1129.860039,987.070007,142.789999,10,390.089995,Consumer,LATAM,Standard Class,South America,Colombia
4,7,579.920013,525.520004,54.400000,7,203.929998,Consumer,LATAM,Second Class,South America,Brasil

## Notebook Summary & Key Learnings

### What I did in this notebook

In this notebook, I started by understanding the dataset and preparing it for further analysis.

- Loaded and explored the dataset
- Checked data types, missing values, and structure
- Realized that the dataset is at **order-item level** (multiple rows per order)
- Since my problem is about **order-level profit**, I aggregated the data to order level
- Verified how profit is stored before aggregation (important step)
- Renamed columns to make them easier to understand
- Created a clean dataset for further analysis

---

### Important thing I learned

One important thing I learned here is that I should not blindly trust column names.

Even though the column was named *"Order Profit Per Order"*, it was actually different for different items in the same order.

So I checked it using `.nunique()` and found that:
- Profit was different across items in many orders
- This means profit was stored at **item level**

Because of this, I used **sum aggregation** to calculate total order profit.

If I had used `first`, the profit calculation would have been wrong.

---

### Key Observations from Data

- The dataset contains around **65,000 orders**, which is good for analysis
- Each order has around **2–3 items on average**
- Most orders are profitable, but some have **very high losses**
- The minimum profit is around **-4300**, which is very large
- Profit values are not evenly distributed (some extreme values exist)
- Discounts vary a lot across orders, which may affect profitability

---

### Business Understanding

From a business point of view:

- Just looking at **sales is not enough**, because some orders still make losses
- Some orders are likely losing money due to:
  - high discounts
  - product combinations
  - or operational factors (like shipping)

This is why predicting **profit risk** is important.

---

### Why this step was important

This step was important because:

- The original dataset structure did not match the business problem
- If I had directly used the raw data, the model would not be meaningful
- Correct aggregation ensures that each row represents one decision unit (one order)

---

### What I will do next

Now that I have a clean order-level dataset, I will:

- Perform Exploratory Data Analysis (EDA)
- Try to understand what factors affect profit
- Identify patterns in low-profit or loss-making orders

---

### Limitations

- Product-level details were reduced after aggregation
- Some useful granular insights might be explored later separately