### 01 — Dataset Understanding

#### Objective
Understand the structure of the Consumer Complaint dataset, identify key columns for analysis, and assess data quality before text preprocessing.

In [1]:
import pandas as pd

In [12]:
data_path = "../data/raw/consumer_complaints.csv"
df = pd.read_csv(data_path)

C:\Users\Abdul Basit\AppData\Local\Temp\ipykernel_11748\2314906332.py:2: DtypeWarning: Columns (4,5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

In [9]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,05/10/2019,Checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,NaN,NaN,NAVY FEDERAL CREDIT UNION,FL,328XX,Older American,NaN,Web,05/10/2019,In progress,Yes,NaN,3238275
1,05/10/2019,Checking or savings account,Other banking product or service,Managing an account,Deposits and withdrawals,NaN,NaN,BOEING EMPLOYEES CREDIT UNION,WA,98204,NaN,NaN,Referral,05/10/2019,Closed with explanation,Yes,NaN,3238228
2,05/10/2019,Debt collection,Payday loan debt,Communication tactics,Frequent or repeated calls,NaN,NaN,CURO Intermediate Holdings,TX,751XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3237964
3,05/10/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Old information reappears or never goes away,NaN,NaN,Ad Astra Recovery Services Inc,LA,708XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3238479
4,05/10/2019,Checking or savings account,Checking account,Managing an account,Banking errors,NaN,NaN,ALLY FINANCIAL INC.,AZ,85205,NaN,NaN,Postal mail,05/10/2019,In progress,Yes,NaN,3238460

In [10]:
df.shape

(1282355, 18)

In [11]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [14]:
df[[
    "Consumer complaint narrative",
    "Date received",
]].isna().sum()

Consumer complaint narrative    898791
Date received                        0
dtype: int64

In [16]:
df_non_empty = df.dropna(subset=["Consumer complaint narrative"])

In [17]:
df_non_empty.shape

(383564, 18)

In [ ]:
df_non_empty["Consumer complaint narrative"].duplicated().sum()

16619

In [21]:
dup_examples = (
    df_non_empty[df_non_empty["Consumer complaint narrative"]
    .duplicated(keep=False)]
    .sort_values("Consumer complaint narrative")
    .head(3)
)

dup_examples[["Consumer complaint narrative", "Complaint ID"]]

                             Consumer complaint narrative  Complaint ID
129045  " " '' I have disputed this Charge Off on this...       3054877
128976  " " '' I have disputed this Charge Off on this...       3054878
127212  " " '' I have disputed this Charge Off on this...       3057449

In [23]:
df_non_empty = df_non_empty.drop_duplicates(
    subset=["Consumer complaint narrative"]
)
df_non_empty.shape

(366945, 18)

In [24]:
df_non_empty.info()

<class 'pandas.core.frame.DataFrame'>
Index: 366945 entries, 29904 to 912553
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Date received                 366945 non-null  object
 1   Product                       366945 non-null  object
 2   Sub-product                   316669 non-null  object
 3   Issue                         366945 non-null  object
 4   Sub-issue                     253716 non-null  object
 5   Consumer complaint narrative  366945 non-null  object
 6   Company public response       173159 non-null  object
 7   Company                       366945 non-null  object
 8   State                         365579 non-null  object
 9   ZIP code                      281422 non-null  object
 10  Tags                          64379 non-null   object
 11  Consumer consent provided?    366945 non-null  object
 12  Submitted via                 366945 non-null  object
 13  Date sent to company          366945 non-null  object
 14  Company response to consumer  366941 non-null  object
 15  Timely response?              366945 non-null  object
 16  Consumer disputed?            160949 non-null  object
 17  Complaint ID                  366945 non-null  int64
dtypes: int64(1), object(17)
memory usage: 53.2+ MB

In [25]:
df_non_empty["Date received"] = pd.to_datetime(df_non_empty["Date received"])

In [28]:
df_non_empty.info()

<class 'pandas.core.frame.DataFrame'>
Index: 366945 entries, 29904 to 912553
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Date received                 366945 non-null  datetime64[ns]
 1   Product                       366945 non-null  object
 2   Sub-product                   316669 non-null  object
 3   Issue                         366945 non-null  object
 4   Sub-issue                     253716 non-null  object
 5   Consumer complaint narrative  366945 non-null  object
 6   Company public response       173159 non-null  object
 7   Company                       366945 non-null  object
 8   State                         365579 non-null  object
 9   ZIP code                      281422 non-null  object
 10  Tags                          64379 non-null   object
 11  Consumer consent provided?    366945 non-null  object
 12  Submitted via                 366945 non-null  object
 13  Date sent to company          366945 non-null  object
 14  Company response to consumer  366941 non-null  object
 15  Timely response?              366945 non-null  object
 16  Consumer disputed?            160949 non-null  object
 17  Complaint ID                  366945 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(16)
memory usage: 53.2+ MB

In [29]:
columns_to_keep = [
    "Date received",
    "Consumer complaint narrative",
    "Product",
    "Issue",
    "Sub-issue",
    "Company"
]

df_step1 = df_non_empty[columns_to_keep].copy()

In [30]:
df_step1.reset_index(drop=True, inplace=True)

In [31]:
output_path = "../data/processed/complaints_step1_filtered.csv"
df_step1.to_csv(output_path, index=False)

### Summary

- Loaded the Consumer Complaint dataset containing more than 1.2 million records.
- Identified the complaint narrative and complaint received date as the primary fields required for NLP and trend analysis.
- Examined missing values and restricted the dataset to complaints with available narrative text.
- Checked for exact duplicate complaint narratives and removed them to avoid over-representation of repeated complaints.
- Converted the complaint received date into datetime format to enable time-based analysis.
- Selected a subset of relevant columns to reduce dataset size and improve processing efficiency.
- Saved a cleaned and filtered dataset (approximately 367k complaints) for use in subsequent NLP steps.